using System;
using NUnit.Framework;
using UnityEngine;
using VRMGames.CartridgeAndCloud.Domain.Customers;
using VRMGames.CartridgeAndCloud.Infrastructure.Customers;

namespace VRMGames.CartridgeAndCloud.Tests.EditMode.Customers
{
    public sealed class CustomerRuntimeTests
    {
        [Test] public void Agent_UnconfiguredTick_DoesNothing() { GameObject go = new GameObject("agent"); try { go.AddComponent<CustomerTechnicalAgentView>().Tick(1f); Assert.That(go.transform.position, Is.EqualTo(Vector3.zero)); } finally { UnityEngine.Object.DestroyImmediate(go); } }
        [Test] public void Agent_NegativeDelta_Throws() { GameObject go = new GameObject("agent"); try { CustomerTechnicalAgentView a = go.AddComponent<CustomerTechnicalAgentView>(); a.Configure(Customer(), new[] { Vector3.zero, Vector3.one, Vector3.right }, 1f, 0.01f, false); Assert.Throws<ArgumentOutOfRangeException>(() => a.Tick(-1f)); } finally { UnityEngine.Object.DestroyImmediate(go); } }
        [Test] public void Agent_WaypointCountMismatch_Throws() { GameObject go = new GameObject("agent"); try { CustomerTechnicalAgentView a = go.AddComponent<CustomerTechnicalAgentView>(); Assert.Throws<ArgumentException>(() => a.Configure(Customer(), new[] { Vector3.zero }, 1f, 0.01f, false)); } finally { UnityEngine.Object.DestroyImmediate(go); } }
        [Test] public void Agent_MovesTowardEntry() { GameObject go = new GameObject("agent"); try { CustomerTechnicalAgentView a = go.AddComponent<CustomerTechnicalAgentView>(); a.Configure(Customer(), new[] { Vector3.right, Vector3.right * 2f, Vector3.right * 3f }, 1f, 0f, false); a.Tick(0.5f); Assert.That(go.transform.position.x, Is.EqualTo(0.5f).Within(0.001f)); } finally { UnityEngine.Object.DestroyImmediate(go); } }
        [Test] public void Agent_ReachingEntry_TransitionsToBrowsing() { GameObject go = new GameObject("agent"); try { CustomerInstance c = Customer(); CustomerTechnicalAgentView a = go.AddComponent<CustomerTechnicalAgentView>(); a.Configure(c, new[] { Vector3.zero, Vector3.right, Vector3.right * 2f }, 1f, 0.01f, false); a.Tick(0f); Assert.That(c.State, Is.EqualTo(CustomerState.Browsing)); } finally { UnityEngine.Object.DestroyImmediate(go); } }
        [Test] public void Agent_BrowsingTicksPatience() { GameObject go = new GameObject("agent"); try { CustomerInstance c = Customer(2); CustomerTechnicalAgentView a = go.AddComponent<CustomerTechnicalAgentView>(); a.Configure(c, new[] { Vector3.zero, Vector3.right * 10f, Vector3.right * 20f }, 1f, 0.01f, false); a.Tick(0f); a.Tick(1f); Assert.That(c.RemainingPatienceSeconds, Is.EqualTo(1)); } finally { UnityEngine.Object.DestroyImmediate(go); } }
        [Test] public void SpawnArea_BuildsRequestedBrowseCountWithinAvailable() { GameObject root = new GameObject("root"); GameObject spawn = new GameObject("spawn"); GameObject entry = new GameObject("entry"); GameObject browse = new GameObject("browse"); GameObject exit = new GameObject("exit"); try { CustomerSpawnAreaAuthoring a = root.AddComponent<CustomerSpawnAreaAuthoring>(); a.Configure(spawn.transform, entry.transform, new[] { browse.transform }, exit.transform); Assert.That(a.BuildNavigationPlan(3, 2).Count, Is.EqualTo(3)); } finally { UnityEngine.Object.DestroyImmediate(root); UnityEngine.Object.DestroyImmediate(spawn); UnityEngine.Object.DestroyImmediate(entry); UnityEngine.Object.DestroyImmediate(browse); UnityEngine.Object.DestroyImmediate(exit); } }
        [Test] public void SpawnArea_MissingEntry_Throws() { GameObject root = new GameObject("root"); GameObject spawn = new GameObject("spawn"); GameObject exit = new GameObject("exit"); try { CustomerSpawnAreaAuthoring a = root.AddComponent<CustomerSpawnAreaAuthoring>(); a.Configure(spawn.transform, null, Array.Empty<Transform>(), exit.transform); Assert.Throws<InvalidOperationException>(() => a.BuildNavigationPlan(1, 0)); } finally { UnityEngine.Object.DestroyImmediate(root); UnityEngine.Object.DestroyImmediate(spawn); UnityEngine.Object.DestroyImmediate(exit); } }

        private static CustomerInstance Customer(int patience = 10) { CustomerInstance c = new CustomerInstance(new CustomerInstanceId("customer"), new CustomerProfileId("profile"), new CustomerNavigationPlan(new[] { new CustomerNavigationTarget(new CustomerNavigationPointId("entry"), CustomerNavigationTargetType.Entry, 0), new CustomerNavigationTarget(new CustomerNavigationPointId("browse"), CustomerNavigationTargetType.Browse, 0), new CustomerNavigationTarget(new CustomerNavigationPointId("exit"), CustomerNavigationTargetType.Exit, 0) }), patience); c.BeginEntering(); return c; }
    }
}
