using System;
using NUnit.Framework;
using UnityEngine;
using VRMGames.CartridgeAndCloud.Domain.Customers;
using VRMGames.CartridgeAndCloud.Infrastructure.Customers;

namespace VRMGames.CartridgeAndCloud.Tests.EditMode.Customers
{
    public sealed class CustomerRuntimeAuthoringTests
    {
        [Test] public void ProfileAsset_BuildsConfiguredProfile() { CustomerProfileAsset a = CreateProfile("p"); try { CustomerProfile p = a.BuildProfile(); Assert.That(p.Id.Value, Is.EqualTo("p")); Assert.That(p.PatienceSeconds, Is.EqualTo(30)); } finally { UnityEngine.Object.DestroyImmediate(a); } }
        [Test] public void ProfileAsset_InvalidWeight_ThrowsOnBuild() { CustomerProfileAsset a = ScriptableObject.CreateInstance<CustomerProfileAsset>(); try { a.Configure("p", "name", Array.Empty<string>(), 0, 30, 1, 1f); Assert.Throws<ArgumentOutOfRangeException>(() => a.BuildProfile()); } finally { UnityEngine.Object.DestroyImmediate(a); } }
        [Test] public void Catalog_BuildsRegistry() { CustomerProfileAsset a = CreateProfile("p"); CustomerProfileCatalogAsset c = ScriptableObject.CreateInstance<CustomerProfileCatalogAsset>(); try { c.Configure(new[] { a }); Assert.That(c.BuildRegistry().Count, Is.EqualTo(1)); } finally { UnityEngine.Object.DestroyImmediate(c); UnityEngine.Object.DestroyImmediate(a); } }
        [Test] public void Catalog_MissingReference_Throws() { CustomerProfileCatalogAsset c = ScriptableObject.CreateInstance<CustomerProfileCatalogAsset>(); try { c.Configure(new CustomerProfileAsset[] { null }); Assert.Throws<InvalidOperationException>(() => c.BuildRegistry()); } finally { UnityEngine.Object.DestroyImmediate(c); } }
        [Test] public void Catalog_DuplicateId_Throws() { CustomerProfileAsset a = CreateProfile("p"); CustomerProfileAsset b = CreateProfile("p"); CustomerProfileCatalogAsset c = ScriptableObject.CreateInstance<CustomerProfileCatalogAsset>(); try { c.Configure(new[] { a, b }); Assert.Throws<ArgumentException>(() => c.BuildRegistry()); } finally { UnityEngine.Object.DestroyImmediate(c); UnityEngine.Object.DestroyImmediate(a); UnityEngine.Object.DestroyImmediate(b); } }
        [Test] public void SpawnSettings_BuildsPolicy() { CustomerSpawnSettingsAsset a = ScriptableObject.CreateInstance<CustomerSpawnSettingsAsset>(); try { a.Configure(6, 8, true); Assert.That(a.BuildPolicy().MaxActiveCustomers, Is.EqualTo(6)); } finally { UnityEngine.Object.DestroyImmediate(a); } }
        [Test] public void SpawnSettings_ZeroCap_ThrowsOnBuild() { CustomerSpawnSettingsAsset a = ScriptableObject.CreateInstance<CustomerSpawnSettingsAsset>(); try { a.Configure(0, 8, true); Assert.Throws<ArgumentOutOfRangeException>(() => a.BuildPolicy()); } finally { UnityEngine.Object.DestroyImmediate(a); } }
        [Test] public void RuntimeAuthoring_PreservesConfiguration() { GameObject go = new GameObject("customer"); CustomerProfileAsset p = CreateProfile("p"); try { CustomerRuntimeAuthoring a = go.AddComponent<CustomerRuntimeAuthoring>(); a.Configure("customer-1", p); Assert.That(a.CustomerInstanceId, Is.EqualTo("customer-1")); Assert.That(a.Profile, Is.SameAs(p)); } finally { UnityEngine.Object.DestroyImmediate(go); UnityEngine.Object.DestroyImmediate(p); } }
        [Test] public void Agent_UnconfiguredTick_DoesNothing() { GameObject go = new GameObject("agent"); try { go.AddComponent<CustomerTechnicalAgentView>().Tick(1f); Assert.That(go.transform.position, Is.EqualTo(Vector3.zero)); } finally { UnityEngine.Object.DestroyImmediate(go); } }
        [Test] public void Agent_NegativeDelta_Throws() { GameObject go = new GameObject("agent"); try { CustomerTechnicalAgentView a = go.AddComponent<CustomerTechnicalAgentView>(); a.Configure(Customer(), new[] { Vector3.zero, Vector3.one, Vector3.right }, 1f, 0.01f, false); Assert.Throws<ArgumentOutOfRangeException>(() => a.Tick(-1f)); } finally { UnityEngine.Object.DestroyImmediate(go); } }
        [Test] public void Agent_WaypointCountMismatch_Throws() { GameObject go = new GameObject("agent"); try { CustomerTechnicalAgentView a = go.AddComponent<CustomerTechnicalAgentView>(); Assert.Throws<ArgumentException>(() => a.Configure(Customer(), new[] { Vector3.zero }, 1f, 0.01f, false)); } finally { UnityEngine.Object.DestroyImmediate(go); } }
        [Test] public void Agent_MovesTowardEntry() { GameObject go = new GameObject("agent"); try { CustomerTechnicalAgentView a = go.AddComponent<CustomerTechnicalAgentView>(); a.Configure(Customer(), new[] { Vector3.right, Vector3.right * 2f, Vector3.right * 3f }, 1f, 0f, false); a.Tick(0.5f); Assert.That(go.transform.position.x, Is.EqualTo(0.5f).Within(0.001f)); } finally { UnityEngine.Object.DestroyImmediate(go); } }
        [Test] public void Agent_ReachingEntry_TransitionsToBrowsing() { GameObject go = new GameObject("agent"); try { CustomerInstance c = Customer(); CustomerTechnicalAgentView a = go.AddComponent<CustomerTechnicalAgentView>(); a.Configure(c, new[] { Vector3.zero, Vector3.right, Vector3.right * 2f }, 1f, 0.01f, false); a.Tick(0f); Assert.That(c.State, Is.EqualTo(CustomerState.Browsing)); } finally { UnityEngine.Object.DestroyImmediate(go); } }
        [Test] public void Agent_BrowsingTicksPatience() { GameObject go = new GameObject("agent"); try { CustomerInstance c = Customer(2); CustomerTechnicalAgentView a = go.AddComponent<CustomerTechnicalAgentView>(); a.Configure(c, new[] { Vector3.zero, Vector3.right * 10f, Vector3.right * 20f }, 1f, 0.01f, false); a.Tick(0f); a.Tick(1f); Assert.That(c.RemainingPatienceSeconds, Is.EqualTo(1)); } finally { UnityEngine.Object.DestroyImmediate(go); } }
        [Test] public void SpawnArea_BuildsRequestedBrowseCountWithinAvailable() { GameObject root = new GameObject("root"); GameObject spawn = new GameObject("spawn"); GameObject entry = new GameObject("entry"); GameObject browse = new GameObject("browse"); GameObject exit = new GameObject("exit"); try { CustomerSpawnAreaAuthoring a = root.AddComponent<CustomerSpawnAreaAuthoring>(); a.Configure(spawn.transform, entry.transform, new[] { browse.transform }, exit.transform); Assert.That(a.BuildNavigationPlan(3, 2).Count, Is.EqualTo(3)); } finally { UnityEngine.Object.DestroyImmediate(root); UnityEngine.Object.DestroyImmediate(spawn); UnityEngine.Object.DestroyImmediate(entry); UnityEngine.Object.DestroyImmediate(browse); UnityEngine.Object.DestroyImmediate(exit); } }
        [Test] public void SpawnArea_MissingEntry_Throws() { GameObject root = new GameObject("root"); GameObject spawn = new GameObject("spawn"); GameObject exit = new GameObject("exit"); try { CustomerSpawnAreaAuthoring a = root.AddComponent<CustomerSpawnAreaAuthoring>(); a.Configure(spawn.transform, null, Array.Empty<Transform>(), exit.transform); Assert.Throws<InvalidOperationException>(() => a.BuildNavigationPlan(1, 0)); } finally { UnityEngine.Object.DestroyImmediate(root); UnityEngine.Object.DestroyImmediate(spawn); UnityEngine.Object.DestroyImmediate(exit); } }

        private static CustomerInstance Customer(int patience = 10) { CustomerInstance c = new CustomerInstance(new CustomerInstanceId("customer"), new CustomerProfileId("profile"), new CustomerNavigationPlan(new[] { new CustomerNavigationTarget(new CustomerNavigationPointId("entry"), CustomerNavigationTargetType.Entry, 0), new CustomerNavigationTarget(new CustomerNavigationPointId("browse"), CustomerNavigationTargetType.Browse, 0), new CustomerNavigationTarget(new CustomerNavigationPointId("exit"), CustomerNavigationTargetType.Exit, 0) }), patience); c.BeginEntering(); return c; }
        private static CustomerProfileAsset CreateProfile(string id) { CustomerProfileAsset a = ScriptableObject.CreateInstance<CustomerProfileAsset>(); a.Configure(id, "name", new[] { "video-game" }, 1, 30, 2, 1.8f); return a; }
    }
}
